#!/bin/sh

start() {
	echo "Starting OpenDCHub"
	start-stop-daemon --start --quiet --exec /usr/bin/opendchub --
}

stop() {
	echo "Stopping OpenDCHub"
	start-stop-daemon --stop --quiet --exec /usr/bin/opendchub
}
	

case "$1" in
start)
	start
	;;
stop)
	stop
	;;
*)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 1
                                                                                                                                        