#!/sbin/runscript

depend() {
        need net
}
        
start() {
        ebegin "Starting XBT Tracker (Telecom)"
        start-stop-daemon --start --quiet -b -m -p /var/run/xbt_tracker-telecom.pid --user xbtt:xbtt --exec /usr/sbin/xbt_tracker-telecom -- --conf_file /etc/xbtt-telecom/xbt_tracker-telecom.conf
        eend $?
}

stop() {
        ebegin "Stopping XBT Tracker (Telecom)"
        start-stop-daemon --stop --quiet --pidfile /var/run/xbt_tracker-telecom.pid
        eend $?
}

