#!/sbin/runscript

depend() {
	need net
}

XBTT_CONFIG=${XBTT_CONFIG:-/etc/xbtt/xbt_tracker.conf}

start() {
        ebegin "Starting XBT Tracker"
        start-stop-daemon --start --quiet --user xbtt:xbtt --exec /usr/bin/xbt_tracker -- --conf_file ${XBTT_CONFIG}
        eend $?
}

stop() {
        ebegin "Stopping XBT Tracker"
        start-stop-daemon --stop --quiet --name ${SVCNAME}
        eend $?
}
