#!/sbin/runscript
# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

depend() {
	need net
}

start() {
	ebegin "Starting fprobe-ulog"
	start-stop-daemon --start --exec /usr/sbin/fprobe-ulog \
		--pidfile ${PIDFILE} \
		-- ${FPROBEULOG_OPTS} >/dev/null 2>&1
	eend $?
}

stop() {
	ebegin "Stopping flow-capture"
	start-stop-daemon --stop --quiet --exec /usr/sbin/fprobe-ulog \
		--pidfile ${PIDFILE}
	eend $?
}
